/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Sat Dec 26 12:01:06 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


